services:
  db:
    image: postgres:16
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

volumes:
  postgres_data: