# Generated by Django 6.0.5 on 2026-07-20 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardware',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-created_at']},
        ),
    ]
